version: "3"

services:
#  db:
#    image: mysql:8.0.23
#    platform: linux/x86_64
#    command: --default-authentication-plugin=mysql_native_password
#    volumes:
#      - "db_app:/var/lib/mysql"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - 3306:3306
#    networks:
#      - symfony
  db:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - symfony


  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/symfony/
    networks:
      - symfony
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/symfony/
    ports:
      - 8080:80
    networks:
      - symfony
    env_file:
      - .env.nginx

volumes:
#  symfony_dockerized_app_sync:
#    external: true
  db-data:

networks:
  symfony: